version: 0.0
Resources:
  - lambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: TestLambdaFunction
        Alias: live
        CurrentVersion: 1
        TargetVersion: 1
