version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: TestLambdaFunction
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2

Hooks:
  BeforeAllowTraffic:
    - location: BeforeAllowTrafficHook
  AfterAllowTraffic:
    - location: AfterAllowTrafficHook
