version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Fetching current Lambda alias version..."
      - CURRENT_VERSION=$(aws lambda get-alias --function-name TestLambdaFunction --name live --query 'FunctionVersion' --output text)
      - echo "Current Version: $CURRENT_VERSION"
      - echo "Publishing a new version..."
      - TARGET_VERSION=$(aws lambda publish-version --function-name TestLambdaFunction --query 'Version' --output text)
      - echo "Target Version: $TARGET_VERSION"
      - sed -i "s/{{CURRENT_VERSION}}/$CURRENT_VERSION/g" appspec.yml
      - sed -i "s/{{TARGET_VERSION}}/$TARGET_VERSION/g" appspec.yml
  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r function.zip . appspec.yml
artifacts:
  files:
    - function.zip
