version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - pip install -r requirements.txt -t .
      - zip -r function.zip . appspec.yml index.py
artifacts:
  files:
    - function.zip
